import { ordersPalette } from '@/theme/theme';

/** Marketplace tokens — Emo AI purple brand (colors only; layout metrics unchanged). */
export const UE = {
  bg: ordersPalette.bg,
  surface: ordersPalette.surfaceSolid,
  surfaceElevated: ordersPalette.surfaceElevated,
  text: ordersPalette.text,
  textSecondary: ordersPalette.textSecondary,
  textMuted: ordersPalette.textMuted,
  border: ordersPalette.border,
  borderLight: ordersPalette.borderMuted,
  accent: ordersPalette.purple,
  accentDark: ordersPalette.purple,
  promo: ordersPalette.danger,
  promoSoft: ordersPalette.dangerSoft,
  gold: ordersPalette.warning,
  black: ordersPalette.text,
  blackBtn: ordersPalette.purple,
  chipActive: ordersPalette.purple,
  chipInactiveBg: ordersPalette.surface,
  chipInactiveText: ordersPalette.text,
  shadow: 'rgba(168, 85, 247, 0.18)',
  radiusXL: 20,
  radiusL: 16,
  radiusM: 12,
  radiusPill: 999,
  fontHero: 28,
  fontTitle: 20,
  fontBody: 16,
  fontCaption: 13,
  fontMicro: 11,
  tabBarHeight: 68,
  cardImageRatio: 0.72,
  /** Layout rhythm */
  spaceSection: 28,
  spaceBlock: 20,
  spaceCard: 16,
  spaceInline: 12,
  restaurantCardWidthRatio: 0.78,
} as const;
