import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import React, { useMemo, useState } from 'react';
import {
  Modal,
  Pressable,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  useColorScheme,
  type StyleProp,
  type ViewStyle,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { foodDescriptionFallback } from '@/lib/foodDescriptionFallback';

const DISCLAIMER = `AI-generated descriptions may be incomplete or contain inaccuracies.
To confirm details about ingredients, allergens, or dietary preferences,
please contact the restaurant directly.`;

export type AIDescriptionProps = {
  description?: string | null;
  title?: string | null;
  category?: string | null;
  compact?: boolean;
  containerStyle?: StyleProp<ViewStyle>;
};

export function AIDescription({
  description,
  title,
  category,
  compact = false,
  containerStyle,
}: AIDescriptionProps) {
  const scheme = useColorScheme();
  const isDark = scheme !== 'light';
  const insets = useSafeAreaInsets();
  const [modalVisible, setModalVisible] = useState(false);

  const stored =
    typeof description === 'string' ? description.trim() : '';
  const fallbackText = useMemo(() => {
    if (stored) return '';
    return foodDescriptionFallback(
      typeof title === 'string' ? title : '',
      category,
    );
  }, [stored, title, category]);

  const displayText = stored || fallbackText;
  const showAiDisclaimer = Boolean(stored);

  if (!displayText) return null;

  const sheetStyles = isDark ? sheetDark : sheetLight;

  return (
    <>
      <View
        style={[
          styles.wrap,
          compact && styles.wrapCompact,
          containerStyle,
        ]}
      >
        <Text style={styles.body}>{displayText}</Text>
        {showAiDisclaimer ? (
          <View style={styles.labelRow}>
            <Text style={styles.label}>Description generated by AI</Text>
            <TouchableOpacity
              onPress={() => setModalVisible(true)}
              hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
              accessibilityRole="button"
              accessibilityLabel="About AI-generated descriptions"
              style={styles.infoHit}
            >
              <MaterialIcons
                name="info-outline"
                size={17}
                color="rgba(148,163,184,0.95)"
              />
            </TouchableOpacity>
          </View>
        ) : null}
      </View>

      <Modal
        visible={modalVisible}
        transparent
        animationType="slide"
        onRequestClose={() => setModalVisible(false)}
      >
        <View style={styles.sheetRoot}>
          <Pressable
            style={styles.sheetBackdrop}
            onPress={() => setModalVisible(false)}
            accessibilityRole="button"
            accessibilityLabel="Dismiss"
          />
          <View
            style={[
              styles.sheetPanel,
              sheetStyles.panel,
              { paddingBottom: Math.max(insets.bottom, 20) },
            ]}
          >
            <View style={[styles.sheetHandle, sheetStyles.handle]} />
            <Text style={[styles.modalTitle, sheetStyles.title]}>
              Description Generated by AI
            </Text>
            <Text style={[styles.modalBody, sheetStyles.body]}>
              {DISCLAIMER}
            </Text>
            <TouchableOpacity
              style={[styles.modalBtn, sheetStyles.btn]}
              onPress={() => setModalVisible(false)}
              activeOpacity={0.85}
            >
              <Text style={[styles.modalBtnText, sheetStyles.btnText]}>
                Got it
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </>
  );
}

const sheetDark = StyleSheet.create({
  panel: {
    backgroundColor: '#141922',
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  handle: { backgroundColor: 'rgba(255,255,255,0.2)' },
  title: { color: '#F8FAFC' },
  body: { color: 'rgba(226,232,240,0.92)' },
  btn: { backgroundColor: 'rgba(255,255,255,0.12)' },
  btnText: { color: '#F8FAFC' },
});

const sheetLight = StyleSheet.create({
  panel: {
    backgroundColor: '#FFFFFF',
    borderTopColor: 'rgba(0,0,0,0.08)',
  },
  handle: { backgroundColor: 'rgba(0,0,0,0.15)' },
  title: { color: '#0F172A' },
  body: { color: 'rgba(51,65,85,0.95)' },
  btn: { backgroundColor: '#0F172A' },
  btnText: { color: '#F8FAFC' },
});

const styles = StyleSheet.create({
  wrap: {
    marginTop: 10,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
  wrapCompact: {
    marginTop: 8,
    paddingTop: 10,
  },
  body: {
    color: 'rgba(248,250,252,0.88)',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '400',
    letterSpacing: 0.1,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  infoHit: {
    marginLeft: 6,
    padding: 2,
  },
  label: {
    color: 'rgba(148,163,184,0.95)',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  sheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetPanel: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 22,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  modalBody: {
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 22,
  },
  modalBtn: {
    alignSelf: 'stretch',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
  },
  modalBtnText: {
    fontWeight: '700',
    fontSize: 16,
  },
});
